name: extension release

on:
  push:
    tags:
    - "v*"

jobs:
  manifest:
    uses: nzbgetcom/nzbget-extensions/.github/workflows/manifest.yml@main

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [manifest]
    uses: nzbgetcom/nzbget-extensions/.github/workflows/extension-release.yml@main
    with:
      release-file-list: main.py manifest.json
      release-file-name: removesamples
      release-dir: RemoveSamples
